services:
  - docker

install:
  - docker pull jjmerelo/perl6-doccer
  - docker images

script:
  - docker run -t -v $TRAVIS_BUILD_DIR:/test --entrypoint=/bin/sh jjmerelo/perl6-doccer
    ./.travis/docker-entrypoint.sh
